manifest:
  remotes:
    # zmk official
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: kuolemax
      url-base: https://github.com/kuolemax
    - name: infused-kim
      url-base: https://github.com/infused-kim
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      # remote: infused-kim
      # revision: my-changes/split-encoder
      # remote: kuolemax
      # revision: encoder-fix
      import: app/west.yml
  self:
    path: config
