manifest:
  remotes:
      # zmk official
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: encoder-fix
      url-base: https://github.com/kuolemax/zmk
  projects:
    - name: zmk
      remote: encoder-fix
      revision: encoder-fix
      import: app/west.yml
  self:
    path: config
